### ISSUE TITLE
Expose auto-evaluator as an API? 

### ISSUE THREAD

**Issue by deepankarm** [rlancemartin/auto-evaluator#12]
Use [langchain-serve](https://github.com/jina-ai/langchain-serve) to expose auto-evaluator as an API to enable integration with external services.

**Comment by PineappleExpress808** [comment]
+1, i am working on this w/ @dankolesnikov and @benisgold.

**Comment by deepankarm** [comment]
@rlancemartin please let me know if any help is needed in the integration.

**Comment by dankolesnikov** [comment]
@deepankarm Yes! We would love help, launching this week.

**Comment by rlancemartin** [comment]
This is done. See:

https://github.com/langchain-ai/auto-evaluator
