### ISSUE TITLE
Would you consider making this a hugging face space?

### ISSUE THREAD

**Issue by datavistics** [rlancemartin/auto-evaluator#2]
https://huggingface.co/spaces

This way its easy to use for anyone. Happy to help if you are interested and have any questions!

**Comment by PineappleExpress808** [comment]
ya, this is a great idea. 

any recommended documentation on process for re-organizing code / deploying to HF?

**Comment by PineappleExpress808** [comment]
Yes, duplicate ticket: 

https://github.com/PineappleExpress808/auto-evaluator/issues/6

Would love this.

**Comment by rlancemartin** [comment]
Done! https://huggingface.co/spaces/rlancemartin/auto-evaluator
